### ISSUE TITLE
大哥，咨询个事儿

### ISSUE THREAD

**Issue by MarvinShawn** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#1]
我的台式机
主板  技嘉B360M AORUS PRO  
CPU 因特尔 i5-8500
显卡  AMD RX580

内存  光威悍将 ddr4 16G（8G*2）
SSD 三星860 evo 250G   目前里面装的是Windows10
SSD 因特尔 760P 256G  想在里面安装mac系统  

用了你的EFI，卡在白苹果logo那里   就是进度条读完了  不进入下一步了。。。。

**Comment by YelCode** [comment]
系统有对应吗？不知道是不是显卡的问题 我现在台式机也不在身边了 而且也没法测试

**Comment by MarvinShawn** [comment]
是对应的   我还去问了下淘宝   有的说能装 有的说不能  都给我整懵逼了。。。   说不能的 也是说580不行   但是  看了远景   A卡更配呀     我再看看  实在不行  花100 淘宝安装算了

**Comment by YelCode** [comment]
去远景论坛 看看情况
大概率是少了AMD驱动 或者是哪里配置需要修改一下
我是直接使用核显的 核显就能4K

**Comment by MarvinShawn** [comment]
> 去远景论坛 看看情况
> 大概率是少了AMD驱动 或者是哪里配置需要修改一下
> 我是直接使用核显的 核显就能4K

好的  3q
