### ISSUE TITLE
请问10.15.4支持Catalina吗

### ISSUE THREAD

**Issue by Mario-Alex** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#10]
如题

**Comment by YelCode** [comment]
Catalina 不就是10.15 
但是10.15.4之前的那几个版本都没试过 bug比较多 所以不尝试
10.15.4 是10.15里面比较稳定的

**Comment by Mario-Alex** [comment]
哈哈哈，明白了EFI后面就是版本号

**Comment by Mario-Alex** [comment]
> Catalina不就是10.15
> 但是10.15.4之前的那几个版本都没试过bug比较多所以不
> 尝试10.15.4是10.15里面比较稳定的
哈哈哈，明白了EFI后面就是版本号

**Comment by Mario-Alex** [comment]
> Catalina 不就是10.15
> 但是10.15.4之前的那几个版本都没试过 bug比较多 所以不尝试
> 10.15.4 是10.15里面比较稳定的

老哥，我能问一下，怎么把EFI从10.14.5更新到10.15.4，10.15.4没有APPLE那个文件夹，我尝试直接替换BOOT和CLOVER文件夹，但是进不去系统
