### ISSUE TITLE
15.4 EFI启动不了Mac OS

### ISSUE THREAD

**Issue by Mario-Alex** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#12]
我用黑果小兵的最新版15.4的镜像重新安装的Mac OS。在安装好后替换成这里的15.4的EFI，启动Mac OS的时候先跑代码，然后就黑屏，没有视频信号了，但是主机好像还在工作。请问大佬，这是因为我哪里的操作不对导致的吗？

**Comment by YelCode** [comment]
可能是EFI不合适 配置一样吗？
我这个是用的DP输出 你是不是用HDMI HDMI我没试过呢

**Comment by Mario-Alex** [comment]
> 可能是EFI不合适 配置一样吗？
> 我这个是用的DP输出 你是不是用HDMI HDMI我没试过呢

是HDMI，可能是因为这个吧；我又回到了Mojave。话说大佬新的EFI什么时候出，到时候我再试试

**Comment by Mario-Alex** [comment]
> 可能是EFI不合适 配置一样吗？
> 我这个是用的DP输出 你是不是用HDMI HDMI我没试过呢

主板、cpu、固态都是一样的

**Comment by Tyningling** [comment]
> > 可能是EFI不合适配置一样吗？
> > 我这个是用的DP输出你是不是用HDMI HDMI我没试过呢
> 
> 主板，cpu，固态都是一样的

emm HDMI真的不能用吗，我正在进行更新....

**Comment by Tyningling** [comment]
# 显然，他是对的
不信邪的我，等待着我的是显示器冰冷的无信号三个字。

**Comment by Tyningling** [comment]
花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。

**Comment by Mario-Alex** [comment]
> 起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。

厉害👍

**Comment by YelCode** [comment]
> 花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。

优秀 到时候可以分享出来呢

**Comment by besteric** [comment]
> 花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。

解决了么，正准备用这个EFI，我也是 HDMI 输出视频信号的哇

**Comment by besteric** [comment]
> > 花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。
> 
> 解决了么，正准备用这个EFI，我也是 HDMI 输出视频信号的哇

一咬牙，硬上，发现DP和HDMI都能正常使用...拆掉 DP，单独使用 HDMI 也没问题...

我配置是技嘉360M+i8400+RX580 8G

**Comment by YumeMichi** [comment]
> > > 花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。
> > 
> > 
> > 解决了么，正准备用这个EFI，我也是 HDMI 输出视频信号的哇
> 
> 一咬牙，硬上，发现DP和HDMI都能正常使用...拆掉 DP，单独使用 HDMI 也没问题...
> 
> 我配置是技嘉360M+i8400+RX580 8G

人家说的是板载的HDMI吧 RX580肯定没问题。。

**Comment by besteric** [comment]
> > > > 花了三个小时，我看起来已经解决了Hdmi的显示问题，我正在进行进一步的优化。
> > > 
> > > 
> > > 解决了么，正准备用这个EFI，我也是 HDMI 输出视频信号的哇
> > 
> > 
> > 一咬牙，硬上，发现DP和HDMI都能正常使用...拆掉 DP，单独使用 HDMI 也没问题...
> > 我配置是技嘉360M+i8400+RX580 8G
> 
> 人家说的是板载的HDMI吧 RX580肯定没问题。。

好吧，目前用下来最大的问题就是 USB 3.0 不生效，刚准备倒腾 200G 的视频素材进去，顿时傻眼了...

另外请教下，如何实用 clover 启动另一个磁盘的 windows 系统呢？目前双硬盘双系统

**Comment by kingyyt** [comment]
意思是没有独显就不能用了吗

**Comment by Tyningling** [comment]
> 意思是没有独显就不能用了吗

可以的，需要你更新最新的驱动，10.15.4对UHD630的驱动有些改动，所以刚放出来的时候很多人会黑屏或者出现一些其他问题，目前的话你只需要更新WEG到最新的1.3.9就可以了。

**Comment by YelCode** [comment]
10.15.6已经提供
