### ISSUE TITLE
会经常死机吗

### ISSUE THREAD

**Issue by niegpie** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#2]
你好，

我的硬件配置:
- CPU i5 8400
- 主板 B360 M AORUS PRO 小雕
- 内存 芝奇 Aegis 16G DDR4
- 固态硬盘 三星 960 EVO （非Plus）
- 显卡 AMD 蓝宝石 RX470d

USB 3.0 正常，休眠OK，所有功能基本完美。
除了一个问题，Mojave 10.14/10.14.3 和 Sierra 10.12.6 下都会经常死机。Windows 正常。

具体表现为：
- 屏幕冻住，无法SSH登录；
- 没有类似白果的弹框（白果会有弹框表示 您的电脑遇到问题）
- 只能强制重启，重启之后也没有可以查看日志的弹框（白果也会有）
- Console 控制台里面也没有相关的日志
- Mojave 比较频繁，基本3小时一次；Sierra 频率不固定，几小时，一天，几天都有可能；

我用 Mojave 的时候有用过你的 EFI，也是会有这个问题。目前在用到 Sierra。
不知道你这套配置是否也有遇到类似的问题，谢谢。

**Comment by YelCode** [comment]
你好 我用10.13.6的时候 很稳定
现在由于xcode的原因 升级了10.14.4 usb3.0失效
但是都没出现死机的问题
我们配置不一样的地方在于显卡 不知道是不是这个造成的

**Comment by MellongLau** [comment]
@lindapao 请问你解决了吗，我现在也遇到卡死重启的问题，时不时出现，有时很稳定，有事开机没多久就卡死重启，我的是集显 UHD630，硬盘是 西数黑盘 M2 SN750。
