### ISSUE TITLE
i7 8700 + B360M-AORUS-PRO 能直接用吗

### ISSUE THREAD

**Issue by ParkinWu** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#4]
i7 8700 + 同款主板，也是只用核显，三星sm961

**Comment by YelCode** [comment]
理论上 没问题的 对应的系统版本对应好
还有就是防止出意外 去远景论坛多下载几个EFI 备用 以防万一
到时候不行 直接替换

**Comment by MellongLau** [comment]
@ParkinWu 我的配置跟你一样，请问你安装成功没有，我的进安装界面没多久就卡死重启了，安装不了。硬盘我是三星的970 evo，不是 plus 版的。

**Comment by ParkinWu** [comment]
> @ParkinWu 我的配置跟你一样，请问你安装成功没有，我的进安装界面没多久就卡死重启了，安装不了。硬盘我是三星的970 evo，不是 plus 版的。

如果是安装剩余2分钟左右卡死重启的话，可以直接再次U盘启动，然后选硬盘，以后可能会多次重启，重启之后还选硬盘就好，如果你用的dp口的话，可以直接用我的，10.14.5，现在看起来一切完美，https://github.com/ParkinWu/EFI-B360-AORUS-PRO-HUD630-8700 @MellongLau

**Comment by MellongLau** [comment]
@ParkinWu 雪中送炭啊，先谢了，等我下班会去就去试试，昨天一直都是进入安装系统界面进度条到10%左右，显示剩下4分钟就重启了，重启后没有硬盘可以选择，我也是用的 DP 口连的显示器，你的镜像是用的小兵的还是直接官方下载？另外，你这个装好后usb3.0能支持吗？有没有已知问题？HDMI 可以支持吗？另外你有没有装 免驱的无线网卡和 wifi？

**Comment by ParkinWu** [comment]
> @ParkinWu 雪中送炭啊，先谢了，等我下班会去就去试试，昨天一直都是进入安装系统界面进度条到10%左右，显示剩下4分钟就重启了，重启后没有硬盘可以选择，我也是用的 DP 口连的显示器，你的镜像是用的小兵的还是直接官方下载？另外，你这个装好后usb3.0能支持吗？有没有已知问题？HDMI 可以支持吗？另外你有没有装 免驱的无线网卡和 wifi？

@MellongLau 我是TB上花80块钱装的原版10.14.5，系统上看是识别出来USB3.1了，速度我没测试，使用过程中没有发现任何问题，CPU变频，睡眠，音频，视频都没问题，用的DP，问店家HDMI需要改动，如果你跟我的硬件一样，可以直接替换EFI就好了

i7 8700
B360-AORUS-PRO
HUD630
三星SM961
DP口显示器
没有其他硬件了

**Comment by MellongLau** [comment]
好的，非常感谢
