### ISSUE TITLE
关于替换EFI

### ISSUE THREAD

**Issue by zgpio** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#5]
```
GIGABYTE-B360M-AORUS-PRO  i5-8500  核显UHD630  HDMI显示器
```
你好，请问烧录了黑果小兵的14.4镜像之后，是替换整个EFI呢，还是只替换EFI/CLOVER？
我已经尝试过以下步骤，但是失败了：
1. 制作黑果小兵14.4安装U盘
2. 通过安装U盘的默认config配置安装mojave
3. 安装之后替换你提供的EFI，但是发现进不了系统了

**Comment by YelCode** [comment]
你好 是替换整个EFI文件夹哈 你再试一下 看看行不行

**Comment by zgpio** [comment]
实际上，我挺困惑的。[macOS安装教程兼小米Pro安装过程记录](https://blog.daliansky.net/MacOS-installation-tutorial-XiaoMi-Pro-installation-process-records.html)中合并EFI小节只覆盖了CLOVER目录，我不清楚APPLE目录对黑苹果是否有用。
还有，请问先替换再安装 和 先安装再替换有什么区别？😅

**Comment by MellongLau** [comment]
请问一下我是同主板，I7 8700的，需要修改什么配置吗，试过直接用你这个EFI禁止安装界面后会很快就卡死重启，不知道是什么问题，我安装的是10.14.4

**Comment by zgpio** [comment]
> 请问一下我是同主板，I7 8700的，需要修改什么配置吗，试过直接用你这个EFI禁止安装界面后会很快就卡死重启，不知道是什么问题，我安装的是10.14.4

你直接用黑果小兵镜像能安装吗？

**Comment by MellongLau** [comment]
@zgpio 已经装上了，之前是三星 970 evo 固态硬盘有质量问题换了个硬盘就好了。

**Comment by zgpio** [comment]
@MellongLau 我看过[支持硬件列表](http://bbs.pcbeta.com/viewthread-1799271-1-1.html), evo应该是支持的，具体是什么问题？

**Comment by MellongLau** [comment]
@zgpio 是的，我的那个是买的硬盘质量有问题，连 win10也会蓝屏重启，mac 安装过程中一直重启，换了硬盘就好。
