### ISSUE TITLE
你好，安装10.14.5 使用对应efi 跑完进度条后黑屏了。。。

### ISSUE THREAD

**Issue by lei-9** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#7]
老哥，我一共遇到两个问题，一个是卡在mbinfo 那里，我改了config 的usb - FixOwnership\Inject 为true 就跑过去了。
另一个问题没解决就是跑完安装进度条就黑屏了，（还没有进行磁盘转换） 说是需要重新安装核显驱动？求帮助。。
我的配置是
8400（核显）
B360M Aorus pro
970 evo
16g 镁光

**Comment by YelCode** [comment]
bios全部根据提示配置了吗？配置中就有核显驱动的

**Comment by lei-9** [comment]
[EFI.zip](https://github.com/YellBinn/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh/files/3417861/EFI.zip)
按照bios设置了。。。
这是我改后的efi 求大佬指点有没有问题。

**Comment by lei-9** [comment]
我用黑苹果小兵自带的efi文件就能进去。。。。

**Comment by YelCode** [comment]
哈哈 那就用小兵的 然后哪些不能用 再改 这样更快

**Comment by lei-9** [comment]
> 哈哈 那就用小兵的 然后哪些不能用 再改 这样更快

老哥，我已经搞好了，还是用了你的efi。是我的步骤错了，我在给安装盘写完镜像后就替换efi文件了。
这个问题我直接用小兵自带的efi就解决了。然后安装完之后显示黑屏，把efi文件改了点东西就好了。目前正常使用了。。 非常感谢你提供这个efi文件。。

**Comment by YelCode** [comment]
哈哈 不客气 可以就好
