### ISSUE TITLE
我用的同一个主板，10.14.6系统，有点问题

### ISSUE THREAD

**Issue by terryops** [YelCode/GIGABYTE-B360M-AORUS-PRO-8400-EFI-Hackintosh#8]
首先非常感谢你让我省了很多工作！直接复制EFI就能大致使用。
但是仍有一些问题：
1. usb-c无法识别。
2. 通过usb hub无法读取u盘。
3. C2000Pro SSD读写速度只有标称的一半。
最关心的是第3个。
不知道你的硬盘速度是否正常？期盼回复。

**Comment by YelCode** [comment]
你好 最近在写代码 主力机 还没升级10.14.6
这边有个教程 关于usb定制的
https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html
固态的话 没有对比过 你最好是用Windows测试 然后看看对比 等我有时间了 再查查

**Comment by terryops** [comment]
好的，感谢！
另外固态硬盘应该是我插到PCIE 3.0 x2的口上去的缘故。
还有，在你的EFI的基础上我加入了NoVPAJpeg.kext解决了独显下预览无法打开，加入了HibernateFixup 解决了休眠唤醒后花屏的问题。

**Comment by YelCode** [comment]
优秀 哈哈 我没有独显 就是拿来敲代码的
